//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avtomatizaciya_zakupki
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отчет о закупках.
    /// </summary>
    // *** Start programmer edit section *** (ОтчетОЗакупках CustomAttributes)

    // *** End programmer edit section *** (ОтчетОЗакупках CustomAttributes)
    [AutoAltered()]
    [Caption("Отчет о закупках")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтчетОЗакупкахE", new string[] {
            "Дата as \'Дата\'",
            "Номер as \'Номер\'",
            "СостояниеОплаты as \'Состояние оплаты\'",
            "СостОтгрузки as \'Сост отгрузки\'",
            "СуммаВклНДС as \'Сумма вкл НДС\'",
            "СуммаДокумента as \'Сумма документа\'",
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "Контрагенты as \'Контрагенты\'",
            "Контрагенты.Контрагент as \'Контрагент\'",
            "Организации as \'Организации\'",
            "Организации.Организация as \'Организация\'",
            "Склады as \'Склады\'",
            "Склады.Склад as \'Склад\'"}, Hidden=new string[] {
            "Контрагенты.Контрагент",
            "Организации.Организация",
            "Склады.Склад"})]
    [AssociatedDetailViewAttribute("ОтчетОЗакупкахE", "Заказ", "ТЧЗаказE", true, "", "Заказ", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ОтчетОЗакупкахE", "Контрагенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Контрагент")]
    [MasterViewDefineAttribute("ОтчетОЗакупкахE", "Организации", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Организация")]
    [MasterViewDefineAttribute("ОтчетОЗакупкахE", "Склады", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Склад")]
    [View("ОтчетОЗакупкахL", new string[] {
            "Дата as \'Дата\'",
            "Номер as \'Номер\'",
            "СостояниеОплаты as \'Состояние оплаты\'",
            "СостОтгрузки as \'Сост отгрузки\'",
            "СуммаВклНДС as \'Сумма вкл НДС\'",
            "СуммаДокумента as \'Сумма документа\'",
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "Контрагенты.Контрагент as \'Контрагент\'",
            "Организации.Организация as \'Организация\'",
            "Склады.Склад as \'Склад\'"})]
    public class ОтчетОЗакупках : IIS.Avtomatizaciya_zakupki.ЗаказПост
    {
        
        private System.DateTime fДата;
        
        // *** Start programmer edit section *** (ОтчетОЗакупках CustomMembers)

        // *** End programmer edit section *** (ОтчетОЗакупках CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОЗакупках.Дата CustomAttributes)

        // *** End programmer edit section *** (ОтчетОЗакупках.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.Дата Get start)

                // *** End programmer edit section *** (ОтчетОЗакупках.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ОтчетОЗакупках.Дата Get end)

                // *** End programmer edit section *** (ОтчетОЗакупках.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.Дата Set start)

                // *** End programmer edit section *** (ОтчетОЗакупках.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ОтчетОЗакупках.Дата Set end)

                // *** End programmer edit section *** (ОтчетОЗакупках.Дата Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОЗакупках.Номер CustomAttributes)

        // *** End programmer edit section *** (ОтчетОЗакупках.Номер CustomAttributes)
        public override int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.Номер Get start)

                // *** End programmer edit section *** (ОтчетОЗакупках.Номер Get start)
                int result = base.Номер;
                // *** Start programmer edit section *** (ОтчетОЗакупках.Номер Get end)

                // *** End programmer edit section *** (ОтчетОЗакупках.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОЗакупках.Номер Set start)

                // *** End programmer edit section *** (ОтчетОЗакупках.Номер Set start)
                base.Номер = value;
                // *** Start programmer edit section *** (ОтчетОЗакупках.Номер Set end)

                // *** End programmer edit section *** (ОтчетОЗакупках.Номер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтчетОЗакупкахE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетОЗакупкахE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетОЗакупкахE", typeof(IIS.Avtomatizaciya_zakupki.ОтчетОЗакупках));
                }
            }
            
            /// <summary>
            /// "ОтчетОЗакупкахL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетОЗакупкахL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетОЗакупкахL", typeof(IIS.Avtomatizaciya_zakupki.ОтчетОЗакупках));
                }
            }
        }
    }
}
