import IISAvtomatizaciya_zakupkiОрганизацииEController from '../i-i-s-avtomatizaciya-zakupki-организации-e';

var IISAvtomatizaciya_zakupkiОрганизацииENewController = IISAvtomatizaciya_zakupkiОрганизацииEController;
export default IISAvtomatizaciya_zakupkiОрганизацииENewController;
